name: Daily Report Generation

on:
  schedule:
    - cron: '17 3 * * *'  # Run at 5:00 AM every day
  workflow_dispatch:      # Allow manual trigger

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    env:
      VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install Dependencies
        run: |
          npm install
          npm install @types/jspdf jspdf jspdf-autotable
          npm install -D typescript @types/node tsx
        
      - name: Build Scripts
        run: |
          npx tsc -p tsconfig.scripts.json
        
      - name: Generate Report
        run: npx tsx scripts/generate-report.ts
