name: Daily Report Generation
on:
  schedule:
    - cron: '55 20 * * *'
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    env:
      VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Build TypeScript
        run: |
          rm -rf dist/
          npx tsc -p tsconfig.build.json --traceResolution
        
      - name: Check Compiled Files
        run: |
          echo "Content of dist directory:"
          ls -R dist/
          echo "Content of pdfExporter.js:"
          cat dist/utils/reports/pdfExporter.js
          
      - name: Generate Report
        run: node scripts/generate-report.js
