name: Generate Daily Report

on:
  schedule:
    - cron: '14 9 * * *' # تشغيل يوميًا الساعة 9:14 صباحًا بالتوقيت UTC
  workflow_dispatch: # للسماح بالتشغيل اليدوي

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # تأكد من أن إصدار Node.js يتوافق مع مشروعك

      - name: Install Dependencies
        run: npm install

      - name: Setup Environment Variables
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

      - name: Generate Daily Report
        run: npm run generate-report

      - name: Commit and Push PDF
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/*.pdf
          git commit -m "Daily Report for $(date +'%Y-%m-%d')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
