name: Daily Report Generation

on:
  schedule:
    - cron: '55 20 * * *'  # Run at 5:00 AM every day
  workflow_dispatch:      # Allow manual trigger

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    env:
      VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npx tsc
        
      - name: Generate Report
        run: node scripts/generate-report.ts
