name: Daily Report Generation

on:
  schedule:
    - cron: '17 3 * * *'  # Run at 5:00 AM every day
  workflow_dispatch:      # Allow manual trigger

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    env:
      VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      NODE_OPTIONS: --experimental-specifier-resolution=node --loader ts-node/esm

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm ci

      - name: Install TypeScript and ts-node
        run: npm install typescript ts-node @types/node --save-dev
        
      - name: Generate Report
        run: node --experimental-specifier-resolution=node --loader ts-node/esm scripts/generate-report.js
